### ISSUE TITLE
Check whether our repository structure works/is correct

### ISSUE THREAD

**Issue by ehuckriede** [ehuckriede/Toronto_renting_regulations#23]
**data/preparation transfer to input, transformation and output**
- [x] Look on the internet and at the grading list for structure repository (output, process and analysis)
- [x] Change data map to input
- [x] Change code ap to process
- [ ] Create new map with output

**Comment by IlsevdBosch** [comment]
Change data map to input.

**Comment by IlsevdBosch** [comment]
Change code map to process.

**Comment by juliehabets** [comment]
Look at the grading criteria for this!!
